# 第一课（命题一）
**在一条有限的直线上构建一个等边三角形。**

第一道证明题在上课之前已经提前要求Alex通读并且思考。在课上，首先Alex在课前已经想过这道证明，并且在课上以和欧几里得同样的思路，通过画圆的方式作出了等边三角形。只是在最后一步的时候需要额外提醒，最后一步并不是“所以三角形ABC是等边三角形”，而是我们必须声明所作等边三角形ABC是构建在AB上的。原因也很简单，是因为命题一是说在一条有限的直线上构建一个等边三角形。那么构建一个等边三角形只是最终完成的一半。我们必须同时声明，这个等边三角形是在这条已知的有限的直线上，这样的证明才是完成的。

第一遍证明完成之后，我们开始一同仔细的审察它。我们会发现，在画圆之后会有一个标记【公设3】。整个命题中一共有四个标记：

 - 【公设3】(公设三：可以以任意圆心和距离画圆。）
 - 【公设1】(公设一：可以从任意一点到另一点画出直线)
- 【定义15】(定义十五： 圆是一个被一条线围成的平面图形，所有从这条线到图形内一点的线段彼此相等。)
 - 【公理1】(公理一：与同一事物相等的事物们彼此互等。)
 
我们的讨论就从这里开始了。

公设和公理的区别是怎样的？

公设的英文是postulate，拉丁语词根postulare，原文古希腊语αιτηματα, (αιτεω)是请求乞求的意思。为什么任意两点之间可以画直线是一条公设，是被乞求所得到的呢？这个问题看似有些无厘头，但其实并不难理解。这么问吧，两点之间是否可以画曲线？可以画出无数种不同样子的线？答案是肯定的。任意两点，中间如何连线，你想让他是什么样子就是什么样子。如此说来，直线是不是就是千千万万个模样中最为特殊且不易得到的一个？将一个小概率事件普遍化，那这不正是我们为了更高的目的向神所乞求来的吗？

公理则不太一样。公理的英文是common notion，原文古希腊语是κοιναι εννοιαι，前者为共同的，通用的，后者则是有标记，想法，概念等含义。“与同一事物相等的事物们彼此互等”，这里存在其它可能性么？是否有一个例子可以说明与同一事物相等的两事物不等？这无疑是很困难的。那么公理则是把已经被广泛接受的通用法则在此标记，毕竟欧几里得只收录了5条公理，并不是每一个已经被广泛接受的通用法则都在书中列出，这样选择的道理之后再论。

在此时此刻，我和Alex达成共识，姑且就先认为公设为实现无数可能性中一个，而公理则是对某一通用道理的陈述。那么基于此，公设三也就不难理解了，以任意点和任意距离作图，作出来的一定是圆么？圆只能在确定圆心和距离的情况下被画出么？这只是跟随着对圆的定义而相应选择的绘制方式。也许想象另外一种方式画圆是很困难的，但是并不证明不存在，假如某一动物遵循某种生物行为，在地上留下了圆的痕迹，既没有圆心，也没有距离，但并不能否认这不是一个圆(尽管似乎也很难证明这就是一个圆)
让我们仔细看圆的定义。“圆是一个被一条线围成的平面图形，所有从这条线到图形内一点的线段彼此相等。“ 当我们思考圆时，圆是那条线还是线里面的图形，还是两者不可分割呢？一个圆铁环是圆么？一个圆的时钟平面是圆么？纯数学概念的圆和现实中具象的关联是怎样的呢？

说到这里，也不得不一起思考什么是定义，为什么我们需要定义。这里和Alex一起讨论了一个非常现代化的例子。大概所有人都知道电脑具体指代的是什么，但是如果我们穿越到几十年几百年几千年前，想和一个从未见过电脑的人描述电脑，该怎么描述呢？如果才能言简意赅的表达出重点？什么样的内容需要出现在定义中？是样式么？是性质么？是功能么？说起电脑和平板，也不得不提Surface这个合二为一的存在，我邀请Alex思考，为什么没有电脑板这个词，而是用Surface这个产品本身的名称。

这个问题在有现实对照的情况下，似乎变得简单了。对于电脑来说，有无数的品牌和样式，台式、笔记本，苹果、联想、外星人等等，电脑是一个大类的总称。而Surface在诸多品牌尚未进入市场开发之前，独领风骚，它自己的名字就是这一类的所有，如果有一天所有品牌都推出了电脑和平板二合一的存在，在诸多不同的选择中，是不是会诞生一个新的词汇来代指这一类呢？还是是电脑本身的定义进行更新呢？

讨论课的每一个问题都没有答案，只有观点，重点也不是最后的答案而是辩论和思考的过程。对于一直以来在传统课堂学习的学生来说，第一步能够开口，主动表达就是很不错的表现。

除了理解这些标注，这个命题中还有一个可以被质疑而往往被忽视的地方，那就是两个圆为什么会相交在点C？这个可以在逻辑上拆解成两个问题，首先为什么两圆相交，其次为什么相交在一点？

*这个问题其实可以延伸创作一个艺术装置。在3D空间中不相交但投影相交的两个圆。

在这里两圆的相交是有隐含条件的：以点AB分别为圆心画的两个圆，是在同一个平面上的。其实以A为圆心AB为半径可以画无数个圆，同样以B为圆心也是一样的，但是所作的两个圆相交，那么必定要在同一平面，这个条件时欧几里得默认而没有说明的。而默认两个圆在同一个平面并且相交后，相交的部分是点，也是不言而喻的，因为两个圆的相交是特别指出的两个线的相交。但是回想一下圆也包括被线所围成的平面图形，在线所围成的平面图形的相交因为看不见就不算相交了吗？

对今天讨论的问题，你是怎么认为的呢？

参考作业：

1. 定义 <br>
假设穿越到古时候，想给一位朋友描述现代生活，提到了电脑和平板，尝试自行定义电脑和平板。<br>
通过搜索引擎寻找电脑和平板的定义，对比自己的定义和公认的定义，你发现了什么？
2. 创作 <br>
用手边的器材做两个同样大小的圆，转换角度看下他们的相交情况。<br>
在灯光下看他们的投影。