# 第八课（命题十一到十三）

## 复习命题十一
**在给定直线的给定点上，画一直线与给定直线呈直角。**

上节课命题十一过得非常快，这里我们先复习一下，在这一次的证明中，我们关注一下欧几里得写证明题的格式。

命题序号：命题十一 

抽象的命题内容：在给定直线的给定点上，画一直线与给定直线呈直角。

将命题内容翻译成具体的图像和字母符号，也就是将命题转化成接下来证明会呈现的内容：<br>
- 设AB为给定直线，且C是其上一给定点。<br>
- 所以要求从点C画一直线与直线AB呈直角。

在具体的图像和符号上的作图和结论：<br>
- 在AC上设任意一点D；作CE使等于CD;【I.3】在DE上构建等边三角形FDE，【I.1】并且连接FC；我说直线FC与给定的直线AB呈直角且起于给定点C。

具体的证明内容：<br>
- 因为DC等于CE，并且CF是公有的，两边DC,CF各自与两边EC,CF互等；且底边DF等于底边FE；所以角DCF等于角ECF; 【I.8】且他们是相邻角。<br>
- 但当一条直线置于另一条直线上，并使得两个相邻角互等，每个角都是直角；【定义十】所以DCF,FCE都是直角。

证完的声明：<br>
- 所以在给定直线AB的给定点C上作的直线CF与AB呈直角。<br>
- Q.E.F.

你会发现欧几里得不是一边画图一边写证明，而是先画图，后证明，是分开的。这说明什么呢？说明《几何原本》这本书里的证明题，他不是对证明过程的简单展示，而是一个证明之后的归纳和整理。就好像是我们写证明题有时候需要一个草稿，最后试卷上写定稿一样，《几何原本》的证明题只是呈现给你了一个定稿。所以有时候我们说他思维缜密，前后连接的非常好，但也未必是从一开始就做到的，也有可能是逐渐补充完善的。它最后完善起来的这个格式非常值得借鉴：

首先每一个命题有一个序号数字能简单的代表它，然后是言简意赅的总结性内容。在证明开始之后，则是先将不易理解的抽象内容通过图像文字符号具象化，然后描述作图构建的步骤，接下来在完整的图像上回到原点，开始证明。证明完成后有声明来标注它的完成。你看它的格式是有始有终的，非常清楚。这种方式特别适用于与人沟通的写作，哪怕不是一道证明题而是一个实验报告，你都可以用这个形式来呈现你的作品，如果是一个报告，那就是以下的模样：

 - 标题、日期(作者)
 - 报告概述(对标题进行进一步的解释，包括概念、方法论等等)
 - 将概念性的问题实践化，描述相关的实验设备、背景，将实验和报告的主题联系在一起
 - 重要的实验步骤和结果
 - 具体的实验过程
 - 最后将实验回归到报告的主题上

这种格式充分考虑了读者的接受度，从主题，概览，到具象化问题，到问题步骤和小结，一应俱全。这个格式运用的思路可以借鉴到不同的报告类文件写作中，这种方式未必呈现一个思考的过程，然而对读者友好，非常的系统化，可读性高。与之相对的就是散文一类的写作，或者由问题出发的探讨，往往这一类写作方式可以呈现作者的思考过程，但是也很容易将读者带偏。在写作的时候，要参考写作对象和目的来选择相应的方式。像数学科学这样的学科，都是带有普遍化目的写作，因而清晰的写作格式和架构就尤为重要；而文学类，更多的是侧重个体经验的描写，从细节处与读者共情，读者接受的不是同样的环境，而是所传递的情感，思考和个体反应，那么格式和架构就不是表达的重点了。

## 命题十二
**给定一无限直线，在线外一给定点上，画垂线。**

命题十二和命题十一是紧密相连的，看起来也有些相似，因而也让我们奇怪，为什么这两个命题不能合放在一起证明？我最开始也以为这里是直角和垂线的递进关系，但后来发现用另一种方式来观察更好：如果仔细阅读两道证明题的表达，会发现在条件中还是略有不同的。命题十一，谈论的还是线上一点，而命题十二，将范围延伸到了线外一点。也就是说，命题十一还在研习“三线合一”的性质之内，还需要借助等边三角形，而命题十二中的垂线则已经走出了三角形顶角/底边的范围, 可以是任意的线外一点与线的关系。

## 命题十三
**如果将一条直线置于另一条直线上成夹角，要么成两直角，要么与两直角相等。**

对于这道命题，Alex最大的困惑就是，一条直线不管和另外一个条线相交是否成夹角，它本身都应该是180度么，即两个直角，为什么还需要这样证明。

这个困惑需要被拆解成两部分：

第一部分是：无论我们用两个直角还是180度描述它，事实上我们想表达的都是一条直线与另一条直线所夹成的角之和不变。而且似乎这个道理从图像上来看是不言自明的。这么说是没错的，所以在这道命题中，我们需要一个度量办法将这个固定的量描述出来。这道命题不仅仅是证明这里有一个等量，而且还要以恰当的方式来表述这个等量，也就是第二部分需要解释的：为什么是用两个直角来表达，而不是180度。

从这门课一开始，Alex学习的一大障碍就是对数的执着。“两个直角”与“180度”这两个概念之间究竟有什么区别？在Alex的眼里，“两个直角”和“180度”指代的都是同一个图像，从这个角度来说，确实是如此的，都是第一部分中所提到的夹角之和，是个等量。然而这两个概念不同的地方在于他们的计量单位是不一样的。“两个直角”是直角乘以2，而“180度”是1度乘以180。我们在定义中有了直角的概念，然而在没有量角器的情况下是没有1度的，也没有180度。也就是说“180度”在现在谈论是缺乏认知基础，即标准的度量单位的。再举个例子，同样一个图像，我也可以说，这是一个平角，但是我们没有定义平角，就有发生误会的可能性，为了避免理解上的歧义，我们就不用未加定义的单位和名词。那么如果我们目前的单位只有直角，没有度数的存在，我们就需要将新生事物“夹角”和直角相比较。

由于以上两个原因，这道命题的存在也就可以被理解了。

另外需要注意的就是这道题的策略，加辅助线画直角。这也不难理解，既然度量单位是直角，最后的量的表达是两个直角，那么自然而然，辅助线需要创造出直角来来作为媒介进行比较和衡量。
