# 第九课（命题十四到十六）

## 命题十四
**如果在任意直线的一点上，有两条直线不在同一侧，且使得所成相邻角等于两直角，则这两条直线在同一直线上。**

这道命题是将命题十三反过来说的。命题十三讲一条直线与另一条直线相交所夹成的角一定等于两直角。命题十四则将其反过来说如果两条直线同中间一条线所成的夹角等于两直角，那么两条直线在同一条直线上。

要理解这两道命题的关系，就不得不补充一个Alex尚未学习到的课外知识：必要充分条件的判定。

我们举几个简单的例子来了解一下以下几个概念：

 - 充分非必要条件 <br>
今天下雨了，空气湿度偏高。<br>
因为雨水的关系，空气湿度变高了。但是空气湿度偏高，也不一定是因为下雨，大量的浇水灌溉，或者不下雨但是起雾的清晨都会导致空气湿度偏高。所以下雨只是无数种可能导致空气湿度偏高的一个原因，我们称之为充分不必要条件。
 - 必要非充分条件 <br>
手机有电，Alex玩手机。<br>
手机有电，Alex才能玩手机，手机没电，Alex就不能玩手机。手机有电是玩手机的必要条件。但是手机有电的时候，Alex不一定在玩手机，可能用来打电话，所以是必要非充分条件。
 - 充分必要条件(充要条件) <br>
Alex考试得了满分，Alex每道题都答对了。<br>
其实充分必要条件就是把同一个意思换成两个方法来讲。<br>
在欧几里得里面，往往定义都是这一类，比如：三角形是等边三角形，三角形的三条边相等。等边三角形的三条边一定相等，三条边相等的三角形一定是等边三角形。这样互相可以推证的是互为充分必要条件。
 - 不必要不充分条件 <br>
今天天气很好，我吃了一颗糖。<br>
昨天天气很好，但我并没有吃糖；我前天吃了一颗糖，但是前天天气不好。由此可见天气好和吃糖并没有直接关系，是个偶然事件，那么它们互为不必要不充分条件。

了解了这四种条件后，我们再来看命题，就明白了，命题十三只能说证明由一个条件推导一个结论，并不能默认由结论可以逆推出条件。所以命题十四，将条件和结论反过来，由此我们知道了夹角为两直角和直线互为充分必要条件。同时命题十四所表述的内容，不在定义里，不在公设里，也不在公理里，所以必然需要证明。

再回顾命题十三和十四，我们也看一下之前欧几里得所作的铺垫，定义八，定义九，十还有公设四：
 - 定义八：平面角是，在同一个平面内，其中一条线与另一条线相交但不重合的倾斜度。
 - 定义九：当包含角的线是直的时候，这个角被称为直线角。
 - 定义十：当一条直线置于另一条直线上，并使得两个相邻角互等，每个角都是直角，置于另一条直线上的这条直线被称为垂直于另一条直线。
 - 公设四：所有的直角彼此相等。

定义九是直线角的定义，它的用处在此处并不明显，但是如果说过圆和直线相切，这个定义就回避了这里的复杂情况，即一个弧线和直线的夹角大小的讨论问题。

定义十则是关于直角和垂直的情况，值得注意，这里直角被定义的时候，不是通过量的大小被定义的，而是通过一个具体现象的描述。也就是说哪怕我们这里有一个和“直角”完全大小相等的角，也不能通过定义直接说是“直角”，因为这里直角的定义需要两条直线和两个相邻角。只有在这个情况下的直角才是直角。也因此在命题十四中，我们需要做辅助线来回溯这个图像来运用直角的概念。也正是命题十四的推导，“直角”不再局限在两条直线相邻的夹角相等，可以脱离这个具体的情景进行使用，“两直角”也因此转化为一个以直角为单位的量，甚至本身作为一个新的单位存在，不需要先构建直角，而可以画一条直线来直接声明两直角的存在。

公设四“所有的直角彼此相等”看起来似乎很奇怪，因为既然直角被定义了，那么所有的角是直角的情况下，不应该理所当然的彼此相等么？如此的话，这应该是个公理而不是公设。我们也许认为欧几里得考虑到了曲面的情况，但又觉得这样理解不对，毕竟任何一个其它的定义和命题都看不到他考虑到曲面。再将定义十和公设四重新联系到一起之后才明白，原来是这样：定义十中的直角是一个现象，而公设四是从现象到度量单位的转化。我们乞求这个转化过程不会出现偏差。公设四，定义十和命题十四一起，再度将直角的概念和应用范围进一步扩大。

另外对于这个命题，Alex也观察到说，要将范围限定到平面之上。在曲面上就不能保证两条直线在同一条线上了。

## 命题十五
**如果两直线相交，他们所成的对顶角互等。**

命题十五非常短，内容也很简单，但是对于命题十五，我还是很意外的。因为Alex竟然没有问我对顶角相等为什么需要证明，“难道不是显而易见的么”？这门讨论课的效果似乎开始变得明显了。我将问题反问回Alex，为什么他不问我这里需要证明，Alex似乎已经逐渐习惯了证明一些似乎自明的命题，用他的话说就是不在定义公理公设中的都需要证明，为什么不写进定义公理公设？因为在创建最开始的基础资料库时，只存放最必须的内容，可以推导的都不放进去。Alex似乎对逻辑的严谨性理解更好了。

## 命题十六
**在任意三角形中，如果延长其中一边，那么外角大于内对角。**

紧接着命题十六，Alex说这不是当然的么，因为外角等于另外两内角之和，那么肯定就会大于其中任一内角。我们一向选择用事实说话，即要求Alex证明外角等于两内角之和。Alex各种尝试，然而发现所需要的定理全都没有证明，比如平行线同位角、内错角相等这些，所以我们最终还是要回到欧几里得看他的证明方式。虽然我们的尝试都失败了，但是这种尝试是值得鼓励的，它帮助Alex理解命题在此处的合理性以及欧几里得证明方法的巧妙。

参考作业：

 - 编程中的if循环，是应用了哪个充分必要条件？你是如何判断的？
