# 第十三课（命题二十五到二十八）

接上节课末尾的二十四，先复习一下，并看命题二十五。

## 命题二十五
**如果两个三角形的两边各自对应相等，但是其中一个底边更长，那么它们的夹角更大。**

命题二十四和命题二十五是连接在一起的，甚至非常相像，都是在固定好三角形的两条边之后，看顶角和底边的关系。命题二十四是说大的顶角对应长的底边，命题二十五则是反过来又证了一遍，长的底边对应大的顶角。如果我们将命题二十四和命题二十五放在一起看，会发现，两个都是归谬法，并且他们反证的方法都是首先排除掉了相等，再排除掉小于的情况。这这里我再一次询问了Alex对反证法的感觉，是否觉得其有足够的说明力，Alex这里用了一个比喻：归谬法好像是二进制，似乎只考虑0和1，那如果还有其它隐藏的情况呢？这个问题很好地揭示了归谬法的局限性，反证，就是证明声明以外的情况是错误的，因此只能承认声明的正确性。

其实这里最薄弱的环节并不是证明其它情况的错误性，而是在枚举所有情况的时候并没有列出所有的可能性。在欧几里得的证明里，是考虑三种情况，大于，等于，和小于。假设我设一个抽象世界是现实生活的翻版，没有完全相同的存在，“不等系统”，那么我在这个新的系统里证明的时候是不是就永远可以不考虑等于的情况？站在欧几里得的系统里，是不是因为相等的可能性存在就能推翻很多“不等系统”里的命题？那么存不存在另一个新的系统与欧几里得系统的关系就如同欧几里得系统与“不等系统”的关系，在另外一个角度可以发现除了大于，小于和等于之外的情况，比如说“约等于”？那么这个时候，归谬法所证明的命题是不是就都失效了呢？而这个“约等于”的存在却不影响其它的证明？那么我们是不是能声明归谬法的论证不够有说服力？

关于命题二十四和命题二十五还有一个值得思考的地方。为什么要证二十四在二十五之前？这里的顺序是否能颠倒呢？如果看证明里的援引，会发现命题二十四需要引用命题二十三，二十三会用到二十二，似乎先二十四后二十五这个顺序是从二十二开始就在准备了，如果我们希望先证长边对大角(二十五)，再证明大角对长边(二十四)，你能做到么？是否需要额外的命题辅助呢？课下不妨仔细思考一下。

## 命题二十六
**如果两个三角形中的两角各自对应相等，并且其中一边等于另一边，即或者等角的临边，或者等角的对边，那么它们剩余的边和角也都对应相等。**

命题二十六很长，Alex说看到就觉得“长，烦，难”，但其实长的命题未必难，有时候有的短命题是另辟蹊径来证明的，反而更难思考，命题二十六只是长，如果我们将它分模块处理，就会变的简洁了。命题二十六主体分为两部分，第一部分是ASA，第二部分是AAS，每个部分分别又都证明在ASA与AAS的情况下，三角形剩余的部分都相等。而且它证明的格式都是一样的，假设剩余的某一组对应的边并不相等，设其中一个边长于另一个，但是这会导致对应的角出现不可能的情况，因此余边必须相等，那么余角也要相等。这样将命题二十六先拆成两半，每部分就都和之前的命题一样不算长了，然后仔细看其中一半，剩余的一半也就很快看懂。

这个命题对之前证明全等的方法进行补充，到此，SSS，SAS, ASA, AAS四种证明全等的方法就都证完了。
在实际的上课过程中，其实是和Alex先一起学习了命题二十七和命题二十八，因为正好学校的数学课也在讲平行，我们不仅一起看了欧几里得的证法，同时看了教材上选读的证明。对比两个证明，我们一致投票给欧几里得。这里之所以可以将学习证明题的顺序进行调换，是因为命题二十七上接的最远的命题是命题十六，从命题十七到命题二十五，和命题二十七并不直接相关。我们可以这么理解，尽管命题后的数字是顺序递增的，而事实上从命题十六之后发展出互不打扰的两个分支，一个是十七到二十五，另一个方向是从二十七开始，这两个方向在之后会交叉。此时我只是希望Alex注意到这一点，在第一卷结束，我会希望Alex能够手绘或者用思维导图做一份命题之间的连接图，从一个更宏观的视角看第一卷四十九个命题的逻辑线。

## 命题二十七
**如果一条直线落在两条直线上并使得内错角互等，那么两条直线平行。**

命题二十七和命题二十八都是与平行相关的，且都是关于判断平行的条件，之后我们会学习平行的性质(命题二十九)。这里我们再次回顾一下平行线的定义：

>定义二十三：平行直线是在同一个平面，向两个方向无限延伸并互不相交的直线。

只看定义二十三，我们也能明白这个定义是无法帮助我们判定一组平行线的，因为它要求在无限远的地方直线仍不相交，而我们的证明题在具象化的时候都是证明在当下，也因此我们需要重新设定其它判定条件，等价于无限延伸且不相交，或者是由于这个无限延伸而不相交进一步推导出来，可以放置于和平行中间的地带，命题二十七就是这样诞生的。内错角互等的情况下，直线两个方向延伸而都不相交，也就满足定义平行了。

## 命题二十八
**如果一条直线落在两条直线上并使得同位角相等，或者同旁内角之和等于两直角，那么两条直线平行。**

命题二十八其实可以拆分成两个小命题：

 - 同位角相等，两直线平行；
 - 同旁内角互补，两直线平行
 
这个证法并没有通过定义直接证明平行，而是转换为命题二十七来证平行，使得步骤更加简练。

参考作业：

 - 在你喜欢的策略类游戏里，找到那些不会立刻起作用但是要提前完成的的游戏操作，并且解释原因。
