# 第十五课（命题三十三到三十六）

这一节课的命题是关于平行四边形的。我们把今天要研讨的命题分为两组，命题三十三和三十四一组，关于平行四边形的定义和性质；命题三十五和三十六一组，关于面积相等概念的转移。

## 命题三十三 & 三十四
**命题三十三：向同一方向「分别」连接相等且平行线段「端点」的线段也相等且平行。**

**命题三十四：在平行四边形的区域内，对边及对角互等，且对角线平分该区域。**

在命题探讨完三角形，平行之后才轮到平行四边形，然而有意思的是，如果我们回头看定义的顺序，平行四边形其实在定义二十二就已经存在了，但是是在平行直线之前出现的，并没有以平行四边形的名字出现，在定义中也没有用到平行这个概念——对边对角相等但四边不全相等且不为直角的是斜方形？(节选定义二十二)，这里我们不妨停下来想一下，对边对角相等的四边形，两组对边是不是一定平行？那么我们之前为什么不通过平行四边形来证平行线？而是通过了内错角、同位角和同旁内角的关系？这里回顾命题二十三：从给定的直线上一点，构建一个直线角，使等于给定的直线角。在这个证明里面欧几里得就是把角放在三角形里面，通过证明三角形全等来证两直线角相等的。

大概三角形和平行四边形有一个不同的地方。平行四边形是两组平行线，并且一组平行线是可以独立存在的，当两组平行线在特定的情况下产生交叉，才会出现一个平行四边形。两组平行线互相依赖产生新的图形，而平行这个概念却是可以从四边形中独立出来的。三角形是可以视为一条直线折两折之后的图形，与它相关的延长线，外角等都依赖于三角形存在，它本身已拆无可拆。因为三角形可以作为一个基本单位，而平行四边形不可以。

于是在命题的学习中，我们先了解平行的概念，然后在一组平行线上搭建另一组平行线，就构建了一个平行四边形，然后证明它的性质满足于“对边对角相等但四边不全相等且不为直角”这个定义的部分，之后两者的概念才产生重合，也完成了从已知到被证明的角色转换。命题三十三就是在平行的基础上搭建平行四边形，而命题三十四证明了平行四边形的对边对角互等。很有意思的是，命题三十三的行文中并没有提到“平行四边形”，而只是说另一组对边平行且相等，而命题三十四就紧接着以平行四边形的区域开篇了。

在命题三十四中，出现了”area“，并没有被定义，而在之后会演变为面积，现在姑且让我们用“区域”来描述它，也就是被线圈定的地方。之前我们谈论过角的平分，线的平分，却是第一次谈论图形的平分。在命题九中，我们曾用两个全等三角形，来确认平面角是被平分了，也就是我们先确认了两个图形的相等性，然后又取出了其中角的部分。而这里，我们第一次直接的谈论图形(区域)。

这里可以引发无数的想象和思考，这个图形是什么样子的？是虚幻还是实体，是被线条如同栅栏般圈起来的封闭内容么？还是与线条紧密相连不可分割的存在？它本身可以和图形分离出来么？在生活中似乎两者例子都能找到的，比如说院子，那么线条就是围墙，而计算院子内的面积，是和墙本身分离的，因为希望知道院子的土地面积，可以种多少花花草草。而如果买一个生日蛋糕，就又是另一码事了，蛋糕的边缘和蛋糕本身是一个整体，图形和边是连续在一起的，我们对院子和蛋糕分别进行抽象化处理，都是几何图形，而边和内里区域的关系却大不相同，这能带给我们什么样的思考呢？

## 命题三十五 & 三十六
**命题三十五：同底且在同组平行线之间的平行四边形互等。**

**命题三十六：等底且在同组平行线之间的平行四边形互等。**

以上两个命题的证明方法并不难，命题三十五的证法是对等量减去等量又添加等量的方法，而命题三十六在之前命题的基础上，只需要找到合适的媒介作为中间桥梁就可以了。

有意思的是相等概念的扩充。相等这个比较的行为是从来没有被定义过的，它似乎是从现实生活中的概念直接拿过来用的，之前我们所证明的事物大多是因为重合而相等，也就是说希望被证明相等的部分可以作为一个连续的整体，每一个不可切割的部分都能一一对应。因为重合的物体是可以分开的，那么经过运动，先重合又不重合的两个物体就是相等的，这里的分离运动有一个假设的前提，就是它的分离必须是无任何损耗的。比如说平移，翻转，对称这些运动，我们假设在抽象几何世界中，不会产生任何能量的损耗，这才会有运动分离之后的相等性。(对于一个位移的物体，也有这样的运动前提，我们假设了这个物体在位移中没有损耗，否则运动前的它和运动后的它就不一样了)

相等的第一步，是从重合到局部分离，也就是命题三十五的同底，然后则是完整的分离，命题三十六中已经变为了等底，同时，在两个命题中，都隐含着脱离形状桎梏的情况，同底但角并不同，在同组平行线之间的同底平行四边形，形状并不一样，而在命题三十五中也被证明了他们的相等性，是以拼接的方式完成的，也就是说我们可以将两个平行四边形进行切割组合，他们所分成的部分，在形状上是一致的，由此推出整体的相等性。这就是改变视角，回到局部和微观部分进行证明的例子。如果我们认可了这样的逻辑跳跃，那么几何会突破我们的视野限制，带我们进行到接近无限的情况。想象一个接近与一根直线的平行四边形，它的底固定，而斜边接近无限长，虽然不知道到底有多长，但是它的面积却是已知的，因为可以通过同底同组平行线之间的其它平行四边形得知，这一个从无限到有限的跳跃，很是值得玩味。