# 第十六课（命题三十七到四十二）
命题三十七和三十八是对命题三十五和三十六的一个再加工，紧接着，我们将条件翻转，在命题三十九和命题四十以图形来倒推平行线。四十一是一个拓展，而四十二是在这一系列基础上的一个再创造。这些命题本身都很短，在掌握命题三十五和三十六的基础上，证明过程也相对简单。

## 命题三十七
**同底且在同组平行线之间的三角形互等。**

命题三十七是命题三十六的一个延续，在证明平行四边形是等量的基础上，证明等量的一半也相等即可。在命题二十三的时候我们提到过不同的证明思路，此处是运用了以大推小的填充对比法。之前我们为了对比角的大小，倒回三角形的层级来进行比较，而现在我们为了证明三角形的大小，更进一步推到了平行四边形的比较上。然而有趣的是，如果我们用宏观的视角来看第一卷，它基本上是遵循从角到图形顺序，然后每一次的跳跃又都可以倒回一小步对之前局部的性质进一步说明。其实这也给我们一个生活和学习上的启示，有些成果是在一个部分进行细加工得来的，而有些成果的发现则需要跨越视角后在看，在同一个知识点不需要过去求善求美，学到更深的内容的时候会理解的更好。

另外命题三十七里比较争议的其实就是最后一步，我们是否可以理所当然的使用“等量的一半也相等”这个论证。因为在公理对等量的运算中，是不涉及乘法和除法的，只是说了加减相等的量也相等。我们可以将论证内容改写为，等量减去一半量后也相等，这是就是运用了公理三，但是怎么才能如何将量取一半呢？这里也就是命题三十四提到的对角线平分平行四边形的部分了。注意这里对公理三的改写运用是有争议的，但是此处合理，是因为平分平行四边形在命题三十四那里得到了证明。

## 命题三十八
**等底且在同组平行线之间的三角形互等。**

命题三十七和三十八的顺序是完全复制了命题三十五和命题三十六。与命题三十七相同，命题三十八只是在证明同样条件下平行四边形相等的基础上加了最后一句相等的量的一半也相等，就结束了证明，同样的方法和争论不再赘述。

## 命题三十九
**同底的同侧全等三角形在同组平行线之间。**

之前的命题是是通过平行线和底边的关系来证明三角形之间的联系，现在则是限定三角形来看平行线。让我们来思考一下，平行线意味着什么？首先，如果我们只是有两个同侧同底的三角形，这个共同的底边就是其中一条平行线的一部分，然后另一条平行线在最开始是不显示出来的(注意，这里不能说不存在，因为它一直存在，只是我们有没有发现它且将它标出来)，是需要我们连接两个三角形的顶点才能绘制出这条平行线的一部分。那么画出的这条平行线其实是在一定程度上圈定了三角形的领域范围，也就是上下的边界，而这个被找到的边界之间有着平行的关系。这能给我们什么启发呢？假设我们在观察一个事物，那么也要去思考一下那些不是偶然的相关联的更大范围事物的性质。由之前的命题得知，这里将两三角形的顶点连线出现的性质并不是一个偶然，这种必然就是新命题值得明确化的方向和内容。

## 命题四十
**等底的同侧全等三角形在同组平行线之间。**

命题四十的来源存疑，被记载是编者后期补充的，然而它承接命题三十九，同时它从“同底”到“等底”的平行变换符合欧几里得之前证明题的作风， 我个人认为，哪怕它是编者补充的，保留下来也无可厚非。

## 命题四十一

**如果一个平行四边形和一个三角形共底且在同组平行线之间，那么此平行四边形是三角形的两倍。**

在将平行四边形和三角形在底边相等且同组平行线之间的情况分别证完以后，(额外又增添了反证平行线内容)，终于我们看到了将平行四边形和三角形整合在一起的证明。命题四十一就是限定了同底和平行线的条件，将命题三十五和三十七进行了一个推论。此处值得注意的的是两倍的这个概念，不要忘记我们的一个历史遗留问题，命题三十四中关于“area”的讨论，此处的图形面积是否可以进行比较，比较的基准线是什么？尽管书中从来没有提到面积单位的问题，但是在我们进行比较的时候，面积单位是不是已经被假定存在了呢？这一点一直都没有被重视，这个单位的问题我们在第五卷的定义还会进行更进一步的探讨。

## 命题四十二
**用一个给定的直线角构建一个平行四边形，使之等于给定的三角形。**

整本书的开头是在一条直线上构建一个等边三角形。这也不禁让我们思考，数学的意义是在于发现还是创造，或者说再利用？这也是我曾经让Alex想过的一个问题。之后我们还在此构建三角形(命题二十二)，直线角(命题二十三)，画了平行线等。此处是构建平行四边形，但给了两个限定条件，一是限定角的大小，二是限定面积的大小。因为前一道命题已经证明了同底的平行四边形和三角形两倍的面积关系，那么自然而然，同组平行线内，底边一半的平行四边形面积和三角形相等，所以只需要在画平行四边形的时候使得角的大小与给定角相等即可。从命题三十五到这个命题，都是关于同组平行线之间四边形和三角形的来回转化，也是对一类平移转换技巧的反复使用，从重合到局部分离到完全分开，再到整体和部分之间的比较，以及停在重塑，也就是在创造上。数学的目的不仅仅是帮助我们认知自然规律，从一开始就有着再创造的含义。
